name = "cloudflare_temp_email"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"] # 必需，用于邮件解析模块[reference:1]

# --- D1 数据库绑定 (必需) ---
[[d1_databases]]
binding = "DB" # 在 Worker 代码中通过 env.DB 访问
database_name = "cloudflare-tmp-email"
database_id = "aa19caad-a2d1-43f5-8ab0-3d58042351f5" # 从 Cloudflare D1 控制台获取[reference:2]

# --- KV 命名空间绑定 (可选，但推荐) ---
# 用于注册验证码、Telegram Bot 会话等[reference:3]
[[kv_namespaces]]
binding = "KV"
id = "b61260adff8848db92ea503a36d5bc39" # 从 Cloudflare KV 控制台获取[reference:4]

# --- 限流器绑定 (可选) ---
# 用于限制 /api/new_address 请求频率[reference:5]
# [[unsafe.bindings]]
# name = "RATE_LIMITER"
# type = "ratelimit"
# namespace_id = "1001"
# simple = { limit = 10, period = 60 }

# --- 定时任务 (可选) ---
# 用于自动清理过期邮件[reference:6]
[triggers]
crons = ["0 3 * * *"] # 每天凌晨3点执行

# --- 环境变量 (vars) ---
[vars]
# 你的域名列表，支持多个，例如 ["mail.example.com", "temp.example.com"]
DOMAINS = ["yxt-edge.cc.cd"]

# 是否允许用户自行创建邮箱地址
ENABLE_USER_CREATE_EMAIL = true

JWT_SECRET = "gZTVFOGZQM2HcgciYPvP0sIS"
# Admin 控制台密码，不配置则无法访问
ADMIN_PASSWORDS = ["qq493497427"]

# 是否启用 Webhook 推送
ENABLE_WEBHOOK = false

# 清理任务每次处理的记录数
CLEANUP_BATCH_SIZE = 3000


[assets]
directory = "../frontend/dist"
binding = "ASSETS"
